config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => "/cable"

  root to: "pages#index"

  resources :graphs

  namespace :api do
    namespace :v1 do
      resources :graphs
      resources :data_sequences
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_sequence.rb
class DataSequence < ApplicationRecord
  belongs_to :graph
  validates :graph, presence: true
  validates :data, presence: true

  after_commit { DataSequenceUpdateJob.perform_later(self) }
end

app/models/graph.rb
class Graph < ApplicationRecord
  belongs_to :user
  has_many :data_sequences

  validates :user, presence: true
  validates :name, presence: true
  validates :g_type, presence: true
  validates_uniqueness_of :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/data_sequences_controller.rb
class Api::V1::DataSequencesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    @graph = Graph.find(params[:id])

    if @graph
      #authorize @graph
      sequences = @graph.data_sequences
      parser = SequenceParser.new(sequences, multi: true)
      render json: parser.parse.to_json and return
    end

    render json: :error
  end

  def create
    @graph = Graph.find(params[:id])

    if @graph
      @data_sequence = DataSequence.create(data_sequence_params)
      @data_sequence.graph = @graph
      #authorize @graph
      #authorize @data_sequence

      if @data_sequence.save
        render json: @data_sequence.id and return
      end
    end

    render json: :error
  end

  private
  def data_sequence_params
    params.require(:data_sequence).permit(:meta, :data, :series)
  end
end

app/controllers/api/v1/graphs_controller.rb
class Api::V1::GraphsController < ApplicationController
  def graph_params
    params.require(:graph).permit(:name, :type, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  before_action :set_graph, only: [:show, :edit, :update, :destroy]
  #after_action :verify_authorized

  def index
    @graphs = Graph.all
    authorize @graphs
    @graphs = policy_scope(Graph)
  end

  def show
    begin
      @graph_config = JSON.parse(@graph.raw_graph_settings)
    rescue JSON::ParserError
      @graph_config = "";
    end
  end

  def new
    @graph = Graph.new
    authorize @graph
  end

  def create
    @graph = Graph.new(graph_params)
    authorize @graph

    @graph.user = current_user

    if @graph.save
      redirect_to @graph
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @graph.update(graph_params)
      redirect_to @graph
    else
      render :edit
    end
  end

  def destroy
    @graph.destroy
    redirect_to graphs_path
  end

  private
  def graph_params
    params.require(:graph).permit(:name, :g_type, :description, :tag, :raw_graph_settings)
  end

  def set_graph
    @graph = Graph.find(params[:id])
    #authorize @graph
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/graphs/_form.html.erb
<%= form_for(@graph, html: { class: "form-horizontal" } ) do |f| %>
  <div class="input-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="input-group">
    <%= f.label :g_type %>
    <%= f.text_field :g_type, class: "form-control" %>
  </div>

  <div class="input-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="input-group">
    <%= f.label :tag %>
    <%= f.text_field :tag, class: "form-control" %>
  </div>

  <div class="input-group">
    <%= f.label :raw_graph_settings %>
    <%= f.text_area :raw_graph_settings, size: "120x20", class: "form-control" %>
  </div>

  <div class="input-group-btn">
    <%= f.submit "submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/graphs/edit.html.erb
<%= render "form" %>

app/views/graphs/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th>User</th>
      <th>Tag</th>
      <th>Sequences</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @graphs.each do |graph| %>
        <tr>
          <td> <%= link_to graph.id, graph %> </td>
          <td> <%= graph.name %> </td>
          <td> <%= graph.g_type %> </td>
          <td> <%= graph.description %> </td>
          <td> <%= graph.user.email %> </td>
          <td> <%= graph.tag %> </td>
          <td> <%= graph.data_sequences.count %> </td>
          <td> 
            <%= link_to "view", graph_path(graph) %> 
            <%= link_to "edit", edit_graph_path(graph) %> 
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "new", new_graph_path, class: "btn btn-default" %>
</div>

app/views/graphs/new.html.erb
<%= render "form" %>

app/views/graphs/show.html.erb
<%= react_component 'ChartContainer', 
    options: @graph_config, 
    graph_id: @graph.id, 
    ajax_path: api_v1_data_sequence_path(@graph.id)
%>

<table class="table">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th> Type </th>
      <th> Desc </th>
      <th> User </th>
      <th> Tag </th>
      <th> Sequences </th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @graph.id %> </td>
      <td> <%= @graph.name %> </td>
      <td> <%= @graph.description %> </td>
      <td> <%= @graph.g_type %> </td>
      <td> <%= @graph.user.email %> </td>
      <td> <%= @graph.tag %> </td>
      <td> <%= @graph.data_sequences.count %> </td>
      <td>
        <%= link_to "edit", edit_graph_path(@graph) %> 
      </td>
    </tr>
  </tbody>
</table>

<div> 
  <pre> <%= @graph.raw_graph_settings %> </pre>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsForce</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">pipe.xyz</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <% if current_user %>
              <li> <%= link_to "Graphs", graphs_path %> </li>
              <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
            <% else %> 
              <li> <%= link_to "Login", new_user_session_path %> </li>
              <li> <%= link_to "Register", new_user_registration_path %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>